title:            Hao's Thought Works
tagline:          Data driving world
description:      ""
logo:             site-logo.png
disqus_shortname: haoch
# Comment out url when working locally to resolve base urls correctly
url:              http://www.haoch.me

# Owner/author information
owner:
  name:           Hao
  avatar:         bio-photo-200x200.png
  bio:            "Java & Python programmer with big data"
  email:          cn.haochen@gmail.com
  twitter:        hchen7
  facebook:       haochencn
  github:         haoch
  linkedin:       ihaochen
  instagram:      haochen90
  weibo:          haochencn
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    "https://plus.google.com/103688232748743092549"

google_analytics: UA-40551822-2
google_verify: 
bing_verify:   
alexa_verify:  

future:      true
lsi:         false
pygments:    true
markdown:    kramdown
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title.html

# Internal pages/posts to include in top navigation
links:
  - title: About
    url: /about.html
  - title: Articles
    url: /articles
  - title: Tags
    url: /tag/index.html

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: [smart]

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true
  
  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "mademistakes.sublime-project", "mademistakes.sublime-workspace", "codekit-config.json", "Gemfile", "Gemfile.lock", "README.md", "node_modules", "Gruntfile.js", "package.json"]
